from __future__ import annotations

r"""
Investigation 45 — BioHub temporal evidence audit.

Purpose
-------
Test two upstream hypotheses raised after Investigation 42:

1. Temporal STIR-Net should reason in a global-motion-compensated coordinate
   system instead of learning to ignore stage/embryo motion.
2. Trackastra's pre-solver association hypotheses may contain many-to-one
   evidence for segmentation merges that is discarded by the final no-fusion
   tracking graph.

This is an AUDIT, not a training experiment. It never edits canonical
preprocessed data, annotations, or production Trackastra artifacts.

Default sample / annotation contract:
    train/44b6_0113de3b
    annotation set: main
    reviewed frames: 0-39

Outputs:
    runs/stirnet/investigations/45_biohub_temporal_evidence_audit/<volume>/
        summary.json
        component_evidence.csv
        feature_separation.csv
        continuation_geometry.csv
        hypothesis_cache/nodes.csv
        hypothesis_cache/edges.csv
        hypothesis_cache/manifest.json

The hypothesis cache is generated by rerunning ONLY Trackastra neural
prediction on lazy zero-padded globally stabilized raw/label movies. When
production bootstrap_motion.csv exists, its exact motion is reused. For
older/migrated caches that predate that artifact, motion is derived read-only
from the persisted Trackastra graph using the current production robust
estimator. The greedy solver is not rerun.
"""

import argparse
import gc
import json
import math
import os
import pickle
import sys
import time
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment
from scipy.stats import rankdata
from skimage.measure import regionprops_table


def repo_root() -> Path:
    here = Path(__file__).resolve()
    for candidate in (here.parent, *here.parents, Path.cwd().resolve()):
        if (
            (candidate / "dataset_curation").is_dir()
            and (candidate / "learned" / "stirnet").is_dir()
            and (candidate / "src" / "tracking" / "trackastra").is_dir()
            and (candidate / "pyproject.toml").is_file()
        ):
            return candidate
    raise RuntimeError("Could not resolve repository root")


ROOT = repo_root()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from dataset_curation.catalog import BioHubCatalog
from dataset_curation.config import DEFAULT_SPACING_ZYX_UM
from src.io import open_sample
from src.tracking import GlobalMotionConfig, TrackastraConfig
from src.tracking.trackastra.config import GlobalMotionEstimate
from src.tracking.trackastra.engine import load_trackastra_model
from src.tracking.trackastra.global_motion import estimate_global_motion
from src.tracking.trackastra.stabilization import pad_frame_to_canvas

SCRIPT_NAME = "45_biohub_temporal_evidence_audit"
CACHE_VERSION = 1
DEFAULT_SAMPLE = "44b6_0113de3b"
DEFAULT_SPLIT = "train"
DEFAULT_ANNOTATION_SET = "main"
DEFAULT_REVIEWED = "0-39"


def resolve(path: str | Path) -> Path:
    p = Path(path).expanduser()
    return p.resolve() if p.is_absolute() else (ROOT / p).resolve()


def atomic_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        tmp.write_text(json.dumps(payload, indent=2, sort_keys=True, default=_json), encoding="utf-8")
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def atomic_csv(path: Path, frame: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        frame.to_csv(tmp, index=False)
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def _json(value: Any):
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    raise TypeError(type(value).__name__)


def load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise TypeError(f"Expected JSON object in {path}")
    return value


def parse_frames(text: str) -> tuple[int, ...]:
    values: set[int] = set()
    for raw in str(text).split(","):
        token = raw.strip()
        if not token:
            continue
        if "-" in token:
            a, b = (int(v) for v in token.split("-", 1))
            if b < a:
                raise ValueError(f"Invalid descending range {token!r}")
            values.update(range(a, b + 1))
        else:
            values.add(int(token))
    if not values or min(values) < 0:
        raise ValueError("--reviewed-frames must contain non-negative frame IDs")
    return tuple(sorted(values))


def parse_spacing(text: str) -> tuple[float, float, float]:
    values = tuple(float(v.strip()) for v in text.split(","))
    if len(values) != 3 or any(v <= 0 or not math.isfinite(v) for v in values):
        raise ValueError("--spacing-zyx-um must contain three positive finite Z,Y,X values")
    return values


def stat_contract(path: Path) -> dict[str, Any]:
    st = path.stat()
    return {"path": str(path.resolve()), "size": int(st.st_size), "mtime_ns": int(st.st_mtime_ns)}


def safe_ratio(a: float, b: float) -> float:
    if not math.isfinite(float(a)) or not math.isfinite(float(b)) or b <= 0:
        return math.nan
    return float(a) / float(b)


def abs_log_ratio(a: float, b: float) -> float:
    r = safe_ratio(a, b)
    return abs(math.log(r)) if math.isfinite(r) and r > 0 else math.nan


def eq_diameter(volume_um3: float) -> float:
    return 2.0 * ((3.0 * volume_um3) / (4.0 * math.pi)) ** (1.0 / 3.0)


def finite(values: Iterable[float]) -> np.ndarray:
    arr = np.asarray(list(values), dtype=np.float64)
    return arr[np.isfinite(arr)]


def med(values: Iterable[float]) -> float:
    arr = finite(values)
    return float(np.median(arr)) if arr.size else math.nan


def pct(values: Iterable[float], q: float) -> float:
    arr = finite(values)
    return float(np.percentile(arr, q)) if arr.size else math.nan


@dataclass(frozen=True)
class Paths:
    sample: str
    split: str
    annotation_set: str
    zarr: Path
    final_instances: Path
    track_graph: Path
    trackastra_summary: Path
    bootstrap_motion: Path
    instance_annotations: Path
    track_annotations: Path
    output: Path
    frame_count: int
    inference_id: str

    def manual_frame(self, t: int) -> Path:
        return self.instance_annotations / f"manual_instances_t{t:03d}.npy"

    @property
    def track_state(self) -> Path:
        return self.track_annotations / "track_annotations.json"

    @property
    def cache(self) -> Path:
        return self.output / "hypothesis_cache"


def make_paths(args: argparse.Namespace) -> Paths:
    record = BioHubCatalog(args.data_root).get(args.sample_id, split=args.split)
    if record.frame_count is None:
        raise RuntimeError("Could not determine BioHub frame count")
    if not record.paths.inference_complete(frame_count=record.frame_count):
        raise RuntimeError(f"Canonical inference incomplete for {record.split}/{record.volume_id}")
    inference_id = record.paths.inference_id()
    if inference_id is None:
        raise RuntimeError("Canonical inference has no inference_id")

    ann_manifest = record.paths.annotation_manifest(args.annotation_set)
    if not ann_manifest.is_file():
        raise FileNotFoundError(ann_manifest)
    ann = load_json(ann_manifest)
    if str(ann.get("base_inference_id", "")) != str(inference_id):
        raise RuntimeError("Annotation set is not bound to the current canonical inference")

    # New canonical tracking writes bootstrap_motion.csv, but older/migrated
    # curation caches can legitimately predate that artifact.  tracking_complete()
    # intentionally does not require bootstrap_motion.csv, so forcing a tracking
    # rebuild here would both waste time and risk changing the temporal evidence
    # bound to the annotations.  Investigation 45 therefore accepts the existing
    # immutable graph and reconstructs the same robust global-motion estimate
    # in-memory when the CSV is absent.
    motion = record.paths.trackastra_root / "bootstrap_motion.csv"
    tracking_summary = load_json(record.paths.trackastra_summary)

    output = resolve(args.output) if args.output else (
        ROOT / "runs" / "stirnet" / "investigations" / SCRIPT_NAME / record.volume_id
    ).resolve()
    return Paths(
        sample=record.volume_id,
        split=record.split,
        annotation_set=args.annotation_set,
        zarr=record.paths.zarr,
        final_instances=record.paths.final_instances,
        track_graph=record.paths.track_graph,
        trackastra_summary=record.paths.trackastra_summary,
        bootstrap_motion=motion,
        instance_annotations=record.paths.instance_annotations(args.annotation_set),
        track_annotations=record.paths.track_annotations(args.annotation_set),
        output=output,
        frame_count=int(record.frame_count),
        inference_id=str(inference_id),
    )


def load_motion(
    paths: Paths,
    shape_zyx: tuple[int, int, int],
    spacing: tuple[float, float, float],
):
    """Load production motion when available, otherwise derive it read-only.

    The fallback is intentionally based on the already-persisted Trackastra
    solution graph.  It uses the exact current production robust estimator:
    adjacent t->t+1 links only, source out-degree=1, target in-degree=1,
    physical-MAD rejection, and cumulative translation.

    This does NOT rewrite canonical tracking.  The derived CSV is stored only
    below the Investigation-45 output directory for provenance/cache reuse.
    """
    spacing_array = np.asarray(spacing, dtype=np.float64)

    if paths.bootstrap_motion.is_file():
        frame = (
            pd.read_csv(paths.bootstrap_motion)
            .sort_values("frame_from")
            .reset_index(drop=True)
        )
        if len(frame) != paths.frame_count - 1:
            raise RuntimeError("bootstrap_motion.csv has wrong transition count")

        pair = frame[["pair_dz", "pair_dy", "pair_dx"]].to_numpy(np.float64)
        cumulative = np.zeros((paths.frame_count, 3), np.float64)
        cumulative[1:] = frame[
            [
                "cumulative_dz_at_to",
                "cumulative_dy_at_to",
                "cumulative_dx_at_to",
            ]
        ].to_numpy(np.float64)

        check = np.zeros_like(cumulative)
        for t in range(1, paths.frame_count):
            check[t] = check[t - 1] + pair[t - 1]
        error_um = np.linalg.norm(
            (check - cumulative) * spacing_array[None],
            axis=1,
        )
        if float(np.max(error_um)) > 1e-4:
            raise RuntimeError(
                "bootstrap motion cumulative displacement is internally inconsistent"
            )

        align = -np.rint(cumulative).astype(np.int64)
        lo, hi = align.min(0), align.max(0)
        placement = align - lo[None]
        canvas = tuple(
            int(v)
            for v in (
                np.asarray(shape_zyx, dtype=np.int64) + (hi - lo)
            ).tolist()
        )
        persisted = frame[
            [
                "placement_z_at_to",
                "placement_y_at_to",
                "placement_x_at_to",
            ]
        ].to_numpy(np.int64)
        if not np.array_equal(persisted, placement[1:]):
            raise RuntimeError(
                "Reconstructed production stabilization differs from "
                "bootstrap_motion.csv"
            )

        estimate = GlobalMotionEstimate(
            pairwise_float_zyx=pair,
            cumulative_float_zyx=cumulative,
            align_int_zyx=align,
            placement_zyx=placement,
            canvas_shape_zyx=canvas,
            pair_counts=frame["pairs_total"].to_numpy(np.int64),
            inlier_counts=frame["pairs_inlier"].to_numpy(np.int64),
            gate_physical=frame["gate_physical"].to_numpy(np.float64),
            median_residual_physical=frame[
                "median_residual_physical"
            ].to_numpy(np.float64),
            p90_residual_physical=frame[
                "p90_residual_physical"
            ].to_numpy(np.float64),
        )
        source = "persisted_production_bootstrap_motion"
        source_artifact = paths.bootstrap_motion
        derived = False

    else:
        print(
            "[global motion] bootstrap_motion.csv is absent in this migrated/"
            "older tracking cache.",
            flush=True,
        )
        print(
            "[global motion] deriving motion read-only from the persisted "
            "Trackastra graph using the current production robust estimator; "
            "canonical tracking will NOT be rebuilt or modified.",
            flush=True,
        )
        with paths.track_graph.open("rb") as handle:
            graph = pickle.load(handle)

        config = GlobalMotionConfig(
            enabled=True,
            voxel_size_zyx=tuple(float(v) for v in spacing),
            minimum_pairs=10,
            mad_scale=4.0,
            minimum_residual_gate_physical=2.0,
        )
        estimate = estimate_global_motion(
            graph,
            frame_count=int(paths.frame_count),
            spatial_shape_zyx=tuple(int(v) for v in shape_zyx),
            config=config,
        )
        del graph

        derived_path = paths.output / "derived_bootstrap_motion.csv"
        atomic_csv(
            derived_path,
            pd.DataFrame(estimate.records()),
        )
        source = "derived_from_persisted_track_graph"
        source_artifact = derived_path
        derived = True

        pair = estimate.pairwise_float_zyx
        cumulative = estimate.cumulative_float_zyx
        canvas = estimate.canvas_shape_zyx

    pair_um = estimate.pairwise_float_zyx * spacing_array[None]
    cumulative_um = estimate.cumulative_float_zyx * spacing_array[None]
    pair_norm = np.linalg.norm(pair_um, axis=1)

    return estimate, {
        "source": source,
        "source_artifact": str(source_artifact.resolve()),
        "derived_fallback": bool(derived),
        "canonical_tracking_modified": False,
        "pairwise_motion_median_um": float(np.median(pair_norm)),
        "pairwise_motion_p90_um": float(np.percentile(pair_norm, 90)),
        "pairwise_motion_max_um": float(np.max(pair_norm)),
        "cumulative_motion_max_um": float(
            np.max(np.linalg.norm(cumulative_um, axis=1))
        ),
        "minimum_pairs_observed": int(np.min(estimate.pair_counts)),
        "minimum_inlier_pairs": int(np.min(estimate.inlier_counts)),
        "canvas_shape_zyx": [int(v) for v in estimate.canvas_shape_zyx],
    }


@dataclass(frozen=True)
class Cell:
    """Canonical persisted spatial detection used by Investigation 45."""

    frame: int
    label: int
    centroid: np.ndarray
    volume_voxels: int
    volume_um3: float


class Cells:
    def __init__(self, movie, spacing, cumulative):
        self.movie = movie
        self.spacing = np.asarray(spacing, np.float64)
        self.cumulative = np.asarray(cumulative, np.float64)
        self.voxel_um3 = float(np.prod(self.spacing))
        self.cache: dict[int, dict[int, Cell]] = {}

    def frame(self, t: int) -> dict[int, Cell]:
        if t in self.cache:
            return self.cache[t]
        p = regionprops_table(np.asarray(self.movie[t]), properties=("label", "centroid", "area"))
        out = {}
        for lab, z, y, x, area in zip(p["label"], p["centroid-0"], p["centroid-1"], p["centroid-2"], p["area"]):
            lab, area = int(lab), int(area)
            out[lab] = Cell(t, lab, np.asarray([z, y, x], np.float64), area, area * self.voxel_um3)
        self.cache[t] = out
        return out

    def get(self, t: int, lab: int) -> Cell | None:
        return self.frame(t).get(lab)

    def raw_um(self, t: int, lab: int) -> np.ndarray:
        return self.frame(t)[lab].centroid * self.spacing

    def stable_um(self, t: int, lab: int) -> np.ndarray:
        return (self.frame(t)[lab].centroid - self.cumulative[t]) * self.spacing


def ignored_ids(paths: Paths, reviewed: set[int]) -> dict[int, set[int]]:
    if not paths.track_state.is_file():
        return {}
    events = load_json(paths.track_state).get("ignored_events", [])
    out: dict[int, set[int]] = defaultdict(set)
    for event in events:
        if not isinstance(event, dict):
            continue
        for key in ("endpoint", "selected_node"):
            node = event.get(key)
            if isinstance(node, (list, tuple)) and len(node) == 2:
                t, lab = int(node[0]), int(node[1])
                if t in reviewed and lab > 0:
                    out[t].add(lab)
    return dict(out)


def target_frame(paths: Paths, movie, t: int) -> np.ndarray:
    path = paths.manual_frame(t)
    return np.asarray(np.load(path, mmap_mode="r", allow_pickle=False) if path.is_file() else movie[t])


def classify_components(paths: Paths, movie, reviewed: tuple[int, ...], ignored: dict[int, set[int]]) -> pd.DataFrame:
    rows = []
    for t in reviewed:
        base = np.asarray(movie[t]); target = target_frame(paths, movie, t)
        bf, tf = base.reshape(-1), target.reshape(-1)
        active = bf > 0
        b = bf[active].astype(np.int64, copy=False); q = tf[active].astype(np.int64, copy=False)
        stride = max(int(q.max(initial=0)) + 1, 1)
        b2t: dict[int, set[int]] = defaultdict(set); t2b: dict[int, set[int]] = defaultdict(set)
        for encoded in np.unique(b * stride + q).tolist():
            bi, qi = int(encoded // stride), int(encoded % stride)
            b2t[bi].add(qi)
            if qi > 0:
                t2b[qi].add(bi)
        for bi in sorted(int(v) for v in np.unique(base) if int(v) > 0):
            tids = sorted(v for v in b2t.get(bi, set()) if v > 0)
            if set(tids) & ignored.get(t, set()):
                cls = "ignored"
            elif len(tids) == 0:
                cls = "removed"
            elif len(tids) >= 2:
                cls = "merge"
            elif len(t2b.get(tids[0], set())) >= 2:
                cls = "overseg_part"
            else:
                cls = "clean"
            rows.append({"frame": t, "instance_id": bi, "target_class": cls, "target_positive_count": len(tids), "manual_target": paths.manual_frame(t).is_file()})
    result = pd.DataFrame(rows)
    if int((result.target_class == "merge").sum()) == 0:
        raise RuntimeError("No curated merge components found in reviewed frames")
    return result


def dask_movies(paths: Paths):
    import dask.array as da
    source = open_sample(paths.zarr)
    shape = tuple(int(v) for v in source.shape)
    chunks = getattr(source, "chunks", None)
    if chunks is None or len(chunks) != 4:
        chunks = (1, *shape[1:])
    raw = da.from_array(source, chunks=chunks, asarray=False, fancy=False)
    labels_handle = np.load(paths.final_instances, mmap_mode="r", allow_pickle=False)
    labels = da.from_array(labels_handle, chunks=(1, *shape[1:]), asarray=False, fancy=False)
    return source, labels_handle, raw, labels


def build_compact_stabilized_movies(raw_movie, instance_movie, estimate):
    """Lazy stabilization with exactly one delayed full-frame task per timepoint.

    Production build_stabilized_movies() deliberately ends with one full spatial
    frame per Dask chunk because Trackastra normalizes Dask blocks independently.
    However, constructing each padded frame with da.pad() and then
    stack(...).rechunk(full_chunks) can create an enormous intermediate rechunk
    graph on some source-Zarr chunk layouts.

    This Investigation-45-only implementation preserves the same pixel
    semantics and the same final chunk contract, but avoids the pad/stack/rechunk
    graph: each source frame is first represented as one full-frame delayed
    chunk, padded in NumPy when computed, then exposed as one Dask chunk.
    """
    import dask.array as da
    from dask import delayed

    raw_shape = tuple(int(v) for v in raw_movie.shape)
    label_shape = tuple(int(v) for v in instance_movie.shape)
    if raw_shape != label_shape:
        raise ValueError(
            f"Raw/instance movie shape mismatch: {raw_shape} vs {label_shape}"
        )
    if len(raw_shape) != 4:
        raise ValueError(f"Expected (T,Z,Y,X), got {raw_shape}")

    frame_count = int(raw_shape[0])
    original_shape = tuple(int(v) for v in raw_shape[1:])
    canvas_shape = tuple(int(v) for v in estimate.canvas_shape_zyx)
    if estimate.placement_zyx.shape != (frame_count, 3):
        raise ValueError(
            "Motion placement/frame mismatch: "
            f"{estimate.placement_zyx.shape} vs frame_count={frame_count}"
        )

    # One input chunk per complete frame. This is the same normalization
    # requirement as production Trackastra stabilization.
    raw_full = (
        raw_movie.rechunk((1, *original_shape))
        if isinstance(raw_movie, da.Array)
        else da.from_array(
            raw_movie,
            chunks=(1, *original_shape),
            asarray=False,
        )
    )
    labels_full = (
        instance_movie.rechunk((1, *original_shape))
        if isinstance(instance_movie, da.Array)
        else da.from_array(
            instance_movie,
            chunks=(1, *original_shape),
            asarray=False,
        )
    )

    raw_blocks = np.asarray(raw_full.to_delayed(), dtype=object).reshape(frame_count)
    label_blocks = np.asarray(labels_full.to_delayed(), dtype=object).reshape(frame_count)

    def _pad_time_chunk(block_tzyx, placement, canvas):
        block = np.asarray(block_tzyx)
        if block.ndim != 4 or int(block.shape[0]) != 1:
            raise RuntimeError(
                f"Expected one delayed full-frame chunk (1,Z,Y,X), got {block.shape}"
            )
        padded = pad_frame_to_canvas(
            block[0],
            placement_zyx=np.asarray(placement, dtype=np.int64),
            canvas_shape_zyx=tuple(int(v) for v in canvas),
        )
        return padded[np.newaxis, ...]

    raw_frames = []
    label_frames = []
    for t in range(frame_count):
        placement = tuple(int(v) for v in estimate.placement_zyx[t].tolist())

        raw_delayed = delayed(_pad_time_chunk)(
            raw_blocks[t],
            placement,
            canvas_shape,
        )
        label_delayed = delayed(_pad_time_chunk)(
            label_blocks[t],
            placement,
            canvas_shape,
        )

        raw_frames.append(
            da.from_delayed(
                raw_delayed,
                shape=(1, *canvas_shape),
                dtype=raw_full.dtype,
            )
        )
        label_frames.append(
            da.from_delayed(
                label_delayed,
                shape=(1, *canvas_shape),
                dtype=labels_full.dtype,
            )
        )

    stabilized_raw = da.concatenate(raw_frames, axis=0)
    stabilized_labels = da.concatenate(label_frames, axis=0)

    expected_chunks = (
        (1,) * frame_count,
        (canvas_shape[0],),
        (canvas_shape[1],),
        (canvas_shape[2],),
    )
    if stabilized_raw.chunks != expected_chunks:
        raise RuntimeError(
            f"Unexpected stabilized raw chunks: {stabilized_raw.chunks}"
        )
    if stabilized_labels.chunks != expected_chunks:
        raise RuntimeError(
            f"Unexpected stabilized label chunks: {stabilized_labels.chunks}"
        )

    print(
        "[stabilization] compact lazy graph: "
        f"{frame_count} full-frame chunks/movie, canvas={canvas_shape}",
        flush=True,
    )
    return stabilized_raw, stabilized_labels


def hypothesis_contract(paths: Paths, model_name: str, batch_size: int, spacing):
    motion_artifact = (
        paths.bootstrap_motion
        if paths.bootstrap_motion.is_file()
        else paths.output / "derived_bootstrap_motion.csv"
    )
    if not motion_artifact.is_file():
        raise FileNotFoundError(
            "Motion provenance artifact is missing after load_motion(): "
            f"{motion_artifact}"
        )
    return {
        "version": CACHE_VERSION + 3,
        "contract": "compact_lazy_stabilized_trackastra_predict_cuda_fallback_v4",
        "inference_id": paths.inference_id,
        "model_name": model_name,
        "batch_size": int(batch_size),
        "spacing_zyx_um": list(spacing),
        "final_instances": stat_contract(paths.final_instances),
        "motion_artifact": stat_contract(motion_artifact),
        "tracking_summary": stat_contract(paths.trackastra_summary),
        "track_graph": stat_contract(paths.track_graph),
    }



def _cuda_preflight(device: str) -> tuple[bool, dict[str, Any]]:
    """Initialize CUDA/cuBLAS before expensive Trackastra feature extraction.

    CUBLAS_STATUS_NOT_INITIALIZED frequently appears only at the first GEMM.
    Doing a tiny matrix multiply up front lets Investigation 45 fail over to
    CPU before spending ~45 s extracting features on a GPU path that cannot
    actually execute the transformer.
    """
    requested = str(device)
    if not requested.lower().startswith("cuda"):
        return False, {
            "requested_device": requested,
            "cuda_requested": False,
            "cuda_available": None,
        }

    try:
        import torch
    except Exception as exc:
        print(
            f"[cuda preflight] PyTorch unavailable ({exc}); using CPU",
            flush=True,
        )
        return False, {
            "requested_device": requested,
            "cuda_requested": True,
            "cuda_available": False,
            "failure": repr(exc),
        }

    if not torch.cuda.is_available():
        print("[cuda preflight] CUDA is unavailable; using CPU", flush=True)
        return False, {
            "requested_device": requested,
            "cuda_requested": True,
            "cuda_available": False,
        }

    try:
        torch.cuda.empty_cache()
        free_before, total = torch.cuda.mem_get_info()
        # Force lazy CUDA context + cuBLAS initialization now.
        probe = torch.ones((32, 32), device=requested, dtype=torch.float32)
        probe_out = probe @ probe
        torch.cuda.synchronize()
        del probe_out, probe
        torch.cuda.empty_cache()
        free_after, _ = torch.cuda.mem_get_info()
        print(
            "[cuda preflight] PASS "
            f"free={free_after / (1024**3):.2f} GiB / "
            f"{total / (1024**3):.2f} GiB",
            flush=True,
        )
        return True, {
            "requested_device": requested,
            "cuda_requested": True,
            "cuda_available": True,
            "free_before_gib": float(free_before / (1024**3)),
            "free_after_gib": float(free_after / (1024**3)),
            "total_gib": float(total / (1024**3)),
            "cublas_probe": "pass",
        }
    except Exception as exc:
        try:
            torch.cuda.empty_cache()
        except Exception:
            pass
        print(
            "[cuda preflight] FAILED; using CPU instead. "
            f"{type(exc).__name__}: {exc}",
            flush=True,
        )
        return False, {
            "requested_device": requested,
            "cuda_requested": True,
            "cuda_available": True,
            "cublas_probe": "failed",
            "failure": repr(exc),
        }


def _release_trackastra_model(model) -> None:
    if model is not None:
        try:
            del model
        except Exception:
            pass
    gc.collect()
    try:
        import torch
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except Exception:
        pass


def _is_cuda_resource_failure(exc: BaseException) -> bool:
    text = str(exc).lower()
    needles = (
        "cublas_status_not_initialized",
        "cublas_status_alloc_failed",
        "cuda out of memory",
        "outofmemoryerror",
        "cuda error",
    )
    return any(token in text for token in needles)


def hypotheses(
    paths: Paths,
    estimate,
    spacing,
    model_name: str,
    device: str,
    batch_size: int,
    rebuild: bool,
):
    nodes_path = paths.cache / "nodes.csv"
    edges_path = paths.cache / "edges.csv"
    manifest_path = paths.cache / "manifest.json"
    runtime_path = paths.cache / "runtime.json"

    contract = hypothesis_contract(paths, model_name, batch_size, spacing)
    if (
        not rebuild
        and nodes_path.is_file()
        and edges_path.is_file()
        and manifest_path.is_file()
        and load_json(manifest_path) == contract
    ):
        print("[hypothesis cache] reuse", flush=True)
        return pd.read_csv(nodes_path), pd.read_csv(edges_path), contract

    requested_device = str(device)
    use_cuda, cuda_info = _cuda_preflight(requested_device)
    active_device = requested_device if use_cuda else "cpu"

    print(
        "[hypothesis cache] running Trackastra neural prediction only "
        f"(requested={requested_device}, active={active_device})",
        flush=True,
    )

    source = labels_handle = raw = labels = model = None
    started = time.perf_counter()
    attempts: list[dict[str, Any]] = []
    try:
        source, labels_handle, raw, labels = dask_movies(paths)
        sr, sl = build_compact_stabilized_movies(raw, labels, estimate)

        def run_once(run_device: str):
            nonlocal model
            config = TrackastraConfig(
                model_name=model_name,
                mode="greedy",
                device=run_device,
                batch_size=batch_size,
                global_motion=GlobalMotionConfig(
                    enabled=True,
                    voxel_size_zyx=tuple(spacing),
                ),
            )
            model = load_trackastra_model(config)

            if str(run_device).lower().startswith("cuda"):
                try:
                    import torch
                    free, total = torch.cuda.mem_get_info()
                    print(
                        "[cuda] Trackastra model loaded: "
                        f"free={free / (1024**3):.2f} GiB / "
                        f"{total / (1024**3):.2f} GiB",
                        flush=True,
                    )
                except Exception:
                    pass

            run_started = time.perf_counter()
            try:
                prediction = model._predict(
                    sr,
                    sl,
                    batch_size=batch_size,
                )
                attempts.append(
                    {
                        "device": str(run_device),
                        "success": True,
                        "seconds": float(time.perf_counter() - run_started),
                    }
                )
                return prediction
            except Exception as exc:
                attempts.append(
                    {
                        "device": str(run_device),
                        "success": False,
                        "seconds": float(time.perf_counter() - run_started),
                        "error_type": type(exc).__name__,
                        "error": str(exc),
                    }
                )
                raise

        try:
            pred = run_once(active_device)
        except RuntimeError as exc:
            if (
                active_device.lower().startswith("cuda")
                and _is_cuda_resource_failure(exc)
            ):
                print(
                    "[cuda] Trackastra association inference failed with a CUDA/"
                    "cuBLAS resource error. Retrying the same neural model on CPU; "
                    "feature extraction will be repeated, but no canonical "
                    "artifacts are modified.",
                    flush=True,
                )
                _release_trackastra_model(model)
                model = None
                active_device = "cpu"
                pred = run_once(active_device)
            else:
                raise

        node_rows = []
        lookup = {}
        for n in pred["nodes"]:
            c = np.asarray(n["coords"], np.float64)
            row = {
                "node_id": int(n["id"]),
                "frame": int(n["time"]),
                "label": int(n["label"]),
                "z_canvas_vox": float(c[0]),
                "y_canvas_vox": float(c[1]),
                "x_canvas_vox": float(c[2]),
            }
            node_rows.append(row)
            lookup[row["node_id"]] = row

        edge_rows = []
        for (src, dst), score in pred["weights"]:
            a, b = lookup[int(src)], lookup[int(dst)]
            edge_rows.append(
                {
                    "source_node_id": int(src),
                    "target_node_id": int(dst),
                    "source_frame": a["frame"],
                    "source_label": a["label"],
                    "target_frame": b["frame"],
                    "target_label": b["label"],
                    "score": float(score),
                    "accepted_solution_edge": False,
                }
            )

        nodes = pd.DataFrame(node_rows)
        edges = pd.DataFrame(edge_rows)
        if (
            not edges.empty
            and np.any(
                edges.target_frame.to_numpy(np.int64)
                - edges.source_frame.to_numpy(np.int64)
                != 1
            )
        ):
            raise RuntimeError(
                "Expected Trackastra hypotheses to be adjacent-frame only"
            )

        paths.cache.mkdir(parents=True, exist_ok=True)
        atomic_csv(nodes_path, nodes)
        atomic_csv(edges_path, edges)
        atomic_json(manifest_path, contract)
        atomic_json(
            runtime_path,
            {
                "requested_device": requested_device,
                "final_device": active_device,
                "cuda_preflight": cuda_info,
                "attempts": attempts,
                "seconds_total": float(time.perf_counter() - started),
            },
        )

        print(
            f"[hypothesis cache] nodes={len(nodes):,} edges={len(edges):,} "
            f"device={active_device} "
            f"time={time.perf_counter() - started:.1f}s",
            flush=True,
        )
        return nodes, edges, contract
    finally:
        _release_trackastra_model(model)


@dataclass
class Accepted:
    node_to_cell: dict[int, tuple[int, int]]
    edges: set[tuple[int, int, int, int]]
    parent: dict[tuple[int, int], tuple[int, int]]
    outgoing: dict[tuple[int, int], set[tuple[int, int]]]
    metrics: dict[str, Any]


def accepted_graph(paths: Paths, cells: Cells, relevant: set[int], max_error_um: float) -> Accepted:
    with paths.track_graph.open("rb") as f:
        graph = pickle.load(f)
    by_t: dict[int, list[int]] = defaultdict(list)
    for node, data in graph.nodes(data=True):
        if int(data.get("time", -1)) in relevant:
            by_t[int(data["time"])].append(int(node))
    node_map = {}; errors = []; dropped = 0
    for t in sorted(relevant):
        ids = by_t.get(t, []); canon = cells.frame(t)
        valid_ids, coords = [], []
        for node in ids:
            c = np.asarray(graph.nodes[node].get("coords"), np.float64)
            if c.shape == (3,) and np.all(np.isfinite(c)):
                valid_ids.append(node); coords.append(c)
            else: dropped += 1
        if not valid_ids or not canon: continue
        labels = sorted(canon); cc = np.stack([canon[x].centroid for x in labels]); gc_ = np.stack(coords)
        cost = np.linalg.norm((gc_[:, None] - cc[None]) * cells.spacing[None, None], axis=-1)
        gi, ci = linear_sum_assignment(cost); matched = set()
        for a, b in zip(gi.tolist(), ci.tolist()):
            matched.add(a); err = float(cost[a, b])
            if err <= max_error_um:
                node_map[valid_ids[a]] = (t, labels[b]); errors.append(err)
            else: dropped += 1
        dropped += len(valid_ids) - len(matched)
    if errors and pct(errors, 95) > max_error_um:
        raise RuntimeError(f"Accepted graph mismatch: p95={pct(errors,95):.4f} um")
    edges = set(); parent = {}; outgoing: dict[tuple[int, int], set[tuple[int, int]]] = defaultdict(set)
    for s, d in graph.edges:
        a, b = node_map.get(int(s)), node_map.get(int(d))
        if a is None or b is None or b[0] != a[0] + 1: continue
        e = (a[0], a[1], b[0], b[1]); edges.add(e); outgoing[a].add(b)
        if b in parent and parent[b] != a:
            raise RuntimeError(f"Accepted no-fusion invariant violated at {b}")
        parent[b] = a
    return Accepted(node_map, edges, parent, dict(outgoing), {
        "retained_nodes": len(node_map), "dropped_nodes": dropped,
        "coordinate_error_median_um": med(errors), "coordinate_error_p95_um": pct(errors,95),
        "accepted_adjacent_edges": len(edges),
    })


def validate_hypothesis_nodes(nodes: pd.DataFrame, cells: Cells, estimate, relevant: set[int]) -> dict[str, Any]:
    errors = []
    for r in nodes[nodes.frame.isin(sorted(relevant))].itertuples(index=False):
        cell = cells.get(int(r.frame), int(r.label))
        if cell is None:
            raise RuntimeError(f"Hypothesis node t={r.frame} label={r.label} missing from final_instances")
        got = np.asarray([r.z_canvas_vox, r.y_canvas_vox, r.x_canvas_vox], np.float64)
        expected = cell.centroid + estimate.placement_zyx[int(r.frame)]
        errors.append(float(np.linalg.norm((got - expected) * cells.spacing)))
    if errors and pct(errors, 95) > 0.10:
        raise RuntimeError(f"Hypothesis node/canonical centroid mismatch p95={pct(errors,95):.4f} um")
    return {"checked": len(errors), "median_um": med(errors), "p95_um": pct(errors,95), "max_um": max(errors) if errors else math.nan}


def mark_accepted(edges: pd.DataFrame, accepted: Accepted) -> pd.DataFrame:
    result = edges.copy()
    result["accepted_solution_edge"] = [
        (int(r.source_frame), int(r.source_label), int(r.target_frame), int(r.target_label)) in accepted.edges
        for r in result.itertuples(index=False)
    ]
    return result


def predicted_position(source: tuple[int, int], accepted: Accepted, cells: Cells):
    t, lab = source; p = cells.stable_um(t, lab); parent = accepted.parent.get(source)
    if parent is None or parent[0] != t - 1: return p, False
    return p + (p - cells.stable_um(*parent)), True


def inside_current(position_um, t: int, lab: int, movie, cells: Cells) -> bool:
    source_vox = np.asarray(position_um) / cells.spacing + cells.cumulative[t]
    idx = np.rint(source_vox).astype(np.int64); shape = np.asarray(movie.shape[1:])
    if np.any(idx < 0) or np.any(idx >= shape): return False
    z, y, x = map(int, idx.tolist())
    return int(movie[t, z, y, x]) == lab


def evidence_table(classified, edges, accepted: Accepted, cells: Cells, movie, plausible_score: float, strong_score: float, near_radius_dref: float, top_k: int):
    incoming: dict[tuple[int, int], list[Any]] = defaultdict(list)
    for r in edges.itertuples(index=False): incoming[(int(r.target_frame), int(r.target_label))].append(r)
    rows = []
    for target in classified.itertuples(index=False):
        t, lab = int(target.frame), int(target.instance_id); current = cells.frame(t)[lab]
        frame_vols = [c.volume_um3 for c in cells.frame(t).values()]; local_med = float(np.median(frame_vols)); dref = eq_diameter(local_med); radius = near_radius_dref * dref
        all_c = sorted(incoming.get((t, lab), []), key=lambda r: float(r.score), reverse=True)
        plausible = [r for r in all_c if float(r.score) >= plausible_score][:top_k]
        strong = [r for r in all_c if float(r.score) >= strong_score]
        parent = accepted.parent.get((t, lab)); raw_cur, stab_cur = cells.raw_um(t, lab), cells.stable_um(t, lab)
        raw_broken = stable_broken = raw_near = stable_near = 0
        if t > 0:
            for plab in cells.frame(t-1):
                broken = len(accepted.outgoing.get((t-1, plab), set())) == 0
                rd = float(np.linalg.norm(cells.raw_um(t-1, plab)-raw_cur)); sd = float(np.linalg.norm(cells.stable_um(t-1, plab)-stab_cur))
                if rd <= radius: raw_near += 1; raw_broken += int(broken)
                if sd <= radius: stable_near += 1; stable_broken += int(broken)
        rejected = [r for r in plausible if not bool(r.accepted_solution_edge)]
        candidate_broken = sum(len(accepted.outgoing.get((int(r.source_frame), int(r.source_label)), set())) == 0 for r in all_c)
        plausible_broken = sum(len(accepted.outgoing.get((int(r.source_frame), int(r.source_label)), set())) == 0 for r in plausible)
        source_vols = []; pred_d = []; pred_inside = 0; pred_points = []
        for r in plausible:
            src = (int(r.source_frame), int(r.source_label)); sc = cells.get(*src)
            if sc is None: continue
            source_vols.append(sc.volume_um3); pred, _ = predicted_position(src, accepted, cells); pred_points.append(pred)
            pred_d.append(float(np.linalg.norm(pred-stab_cur))); pred_inside += int(inside_current(pred, t, lab, movie, cells))
        parent_vol = cells.get(*parent).volume_um3 if parent is not None and cells.get(*parent) is not None else math.nan
        sum_vol = float(sum(source_vols)) if source_vols else math.nan
        single_err, multi_err = abs_log_ratio(current.volume_um3,parent_vol), abs_log_ratio(current.volume_um3,sum_vol)
        scores = [float(r.score) for r in all_c]
        spread = math.nan
        if pred_points:
            p = np.stack(pred_points); center = p.mean(0); spread = float(np.sqrt(np.mean(np.sum((p-center)**2,axis=1))))
        rows.append({
            "frame":t,"instance_id":lab,"target_class":str(target.target_class),"manual_target":bool(target.manual_target),
            "volume_um3":current.volume_um3,"current_over_local_median_volume":safe_ratio(current.volume_um3,local_med),"dref_um":dref,"near_radius_um":radius,
            "accepted_parent_count":int(parent is not None),"current_is_newborn":bool(parent is None),
            "candidate_predecessor_count":len(all_c),"plausible_predecessor_count":len(plausible),"strong_predecessor_count":len(strong),
            "rejected_plausible_predecessor_count":len(rejected),"candidate_broken_predecessor_count":candidate_broken,"plausible_broken_predecessor_count":plausible_broken,
            "candidate_score_max":max(scores) if scores else math.nan,"candidate_score_sum":sum(scores),"plausible_score_sum":sum(float(r.score) for r in plausible),
            "raw_nearby_predecessor_count":raw_near,"stable_nearby_predecessor_count":stable_near,"raw_nearby_broken_count":raw_broken,"stable_nearby_broken_count":stable_broken,
            "current_over_accepted_parent_volume":safe_ratio(current.volume_um3,parent_vol),"current_over_plausible_volume_sum":safe_ratio(current.volume_um3,sum_vol),
            "single_parent_volume_error":single_err,"multi_parent_volume_error":multi_err,
            "volume_conservation_gain":single_err-multi_err if math.isfinite(single_err) and math.isfinite(multi_err) else math.nan,
            "predicted_center_inside_count":pred_inside,"predicted_to_current_mean_um":float(np.mean(pred_d)) if pred_d else math.nan,
            "predicted_to_current_max_um":max(pred_d) if pred_d else math.nan,"predicted_center_spread_um":spread,
        })
    return pd.DataFrame(rows)


FEATURES = [
    "current_over_local_median_volume","candidate_predecessor_count","plausible_predecessor_count","strong_predecessor_count",
    "rejected_plausible_predecessor_count","candidate_broken_predecessor_count","plausible_broken_predecessor_count",
    "candidate_score_sum","plausible_score_sum","raw_nearby_predecessor_count","stable_nearby_predecessor_count",
    "raw_nearby_broken_count","stable_nearby_broken_count","current_over_accepted_parent_volume",
    "single_parent_volume_error","multi_parent_volume_error","volume_conservation_gain","predicted_center_inside_count",
    "predicted_to_current_mean_um","predicted_to_current_max_um","predicted_center_spread_um",
]


def auc(y, x):
    y = np.asarray(y,np.int64); x=np.asarray(x,np.float64); m=np.isfinite(x); y,x=y[m],x[m]
    p,n=int((y==1).sum()),int((y==0).sum())
    if p==0 or n==0: return math.nan
    ranks=rankdata(x,method="average"); u=float(ranks[y==1].sum())-p*(p+1)/2
    return u/(p*n)


def separation(evidence):
    f=evidence[evidence.target_class.isin(["merge","clean"])].copy(); y=(f.target_class=="merge").astype(int).to_numpy(); rows=[]
    for name in FEATURES:
        x=pd.to_numeric(f[name],errors="coerce").to_numpy(np.float64); a=auc(y,x); m=x[y==1]; c=x[y==0]; m=m[np.isfinite(m)]; c=c[np.isfinite(c)]
        rows.append({"feature":name,"merge_n":len(m),"clean_n":len(c),"merge_median":float(np.median(m)) if len(m) else math.nan,
                     "clean_median":float(np.median(c)) if len(c) else math.nan,"auc_high_is_merge":a,
                     "oriented_auc":max(a,1-a) if math.isfinite(a) else math.nan,
                     "direction":"higher_in_merge" if math.isfinite(a) and a>=.5 else "lower_in_merge"})
    return pd.DataFrame(rows).sort_values("oriented_auc",ascending=False,na_position="last").reset_index(drop=True)


def continuation_table(accepted: Accepted, cells: Cells, reviewed: set[int]):
    rows=[]
    for t0,l0,t1,l1 in sorted(accepted.edges):
        if t1 not in reviewed: continue
        raw=float(np.linalg.norm(cells.raw_um(t1,l1)-cells.raw_um(t0,l0))); stable=float(np.linalg.norm(cells.stable_um(t1,l1)-cells.stable_um(t0,l0)))
        rows.append({"source_frame":t0,"source_label":l0,"target_frame":t1,"target_label":l1,"raw_distance_um":raw,"stable_distance_um":stable,"distance_reduction_um":raw-stable})
    return pd.DataFrame(rows)


def signature(evidence):
    merge=evidence[evidence.target_class=="merge"]; clean=evidence[evidence.target_class=="clean"]
    def rate(frame, fn): return float(np.mean([bool(fn(r)) for r in frame.itertuples(index=False)])) if len(frame) else math.nan
    return {
        "merge_components":len(merge),"clean_components":len(clean),"excluded_components":len(evidence)-len(merge)-len(clean),
        "merge_newborn_rate":rate(merge,lambda r:r.current_is_newborn),
        "merge_retains_parent_rate":rate(merge,lambda r:r.accepted_parent_count>=1),
        "merge_multi_plausible_rate":rate(merge,lambda r:r.plausible_predecessor_count>=2),
        "clean_multi_plausible_rate":rate(clean,lambda r:r.plausible_predecessor_count>=2),
        "merge_many_to_one_suppressed_rate":rate(merge,lambda r:r.plausible_predecessor_count>=2 and r.accepted_parent_count<=1),
        "merge_rejected_plausible_rate":rate(merge,lambda r:r.rejected_plausible_predecessor_count>=1),
        "clean_rejected_plausible_rate":rate(clean,lambda r:r.rejected_plausible_predecessor_count>=1),
        "merge_stable_broken_nearby_rate":rate(merge,lambda r:r.stable_nearby_broken_count>=1),
        "clean_stable_broken_nearby_rate":rate(clean,lambda r:r.stable_nearby_broken_count>=1),
        "merge_parent_volume_gt_1p5_rate":rate(merge,lambda r:math.isfinite(r.current_over_accepted_parent_volume) and r.current_over_accepted_parent_volume>=1.5),
        "clean_parent_volume_gt_1p5_rate":rate(clean,lambda r:math.isfinite(r.current_over_accepted_parent_volume) and r.current_over_accepted_parent_volume>=1.5),
        "merge_multi_volume_better_rate":rate(merge,lambda r:math.isfinite(r.volume_conservation_gain) and r.volume_conservation_gain>0),
        "clean_multi_volume_better_rate":rate(clean,lambda r:math.isfinite(r.volume_conservation_gain) and r.volume_conservation_gain>0),
        "merge_predicted_centers_inside_ge2_rate":rate(merge,lambda r:r.predicted_center_inside_count>=2),
        "clean_predicted_centers_inside_ge2_rate":rate(clean,lambda r:r.predicted_center_inside_count>=2),
    }


def main(args):
    reviewed=parse_frames(args.reviewed_frames); spacing=parse_spacing(args.spacing_zyx_um); paths=make_paths(args); paths.output.mkdir(parents=True,exist_ok=True)
    movie=np.load(paths.final_instances,mmap_mode="r",allow_pickle=False)
    if movie.ndim!=4 or movie.shape[0]!=paths.frame_count: raise RuntimeError("Invalid final_instances movie")
    if max(reviewed)>=paths.frame_count: raise ValueError("Reviewed frame outside movie")
    tracking_summary=load_json(paths.trackastra_summary); production_model=str(tracking_summary.get("model","ctc")); model_name=args.model_name or production_model
    if model_name!=production_model and not args.allow_model_override: raise RuntimeError("--model-name differs from production model; pass --allow-model-override for an explicit ablation")
    estimate,motion_metrics=load_motion(
        paths,
        tuple(int(v) for v in movie.shape[1:]),
        spacing,
    )
    print(
        f"[global motion] source={motion_metrics['source']} "
        f"median={motion_metrics['pairwise_motion_median_um']:.3f}um "
        f"p90={motion_metrics['pairwise_motion_p90_um']:.3f}um",
        flush=True,
    )
    cells=Cells(movie,spacing,estimate.cumulative_float_zyx)
    relevant={tt for t in reviewed for tt in (t-2,t-1,t,t+1) if 0<=tt<paths.frame_count}
    classified=classify_components(paths,movie,reviewed,ignored_ids(paths,set(reviewed)))
    accepted=accepted_graph(paths,cells,relevant,args.graph_match_error_um)
    nodes,edges,cache_manifest=hypotheses(paths,estimate,spacing,model_name,args.device,args.batch_size,args.rebuild_hypothesis_cache)
    node_metrics=validate_hypothesis_nodes(nodes,cells,estimate,relevant); edges=mark_accepted(edges,accepted); atomic_csv(paths.cache/"edges.csv",edges)
    evidence=evidence_table(classified,edges,accepted,cells,movie,args.plausible_score_threshold,args.strong_score_threshold,args.near_radius_dref,args.top_k_predecessors)
    sep=separation(evidence); cont=continuation_table(accepted,cells,set(reviewed)); sig=signature(evidence)
    atomic_csv(paths.output/"component_evidence.csv",evidence); atomic_csv(paths.output/"feature_separation.csv",sep); atomic_csv(paths.output/"continuation_geometry.csv",cont)
    raw=cont.raw_distance_um.to_numpy(np.float64) if len(cont) else np.asarray([]); stable=cont.stable_distance_um.to_numpy(np.float64) if len(cont) else np.asarray([])
    geometry={"accepted_continuations":len(cont),"raw_median_um":float(np.median(raw)) if len(raw) else math.nan,"stable_median_um":float(np.median(stable)) if len(stable) else math.nan,
              "raw_p90_um":float(np.percentile(raw,90)) if len(raw) else math.nan,"stable_p90_um":float(np.percentile(stable,90)) if len(stable) else math.nan,
              "fraction_tighter_after_compensation":float(np.mean(stable<raw)) if len(raw) else math.nan}
    summary={"investigation":SCRIPT_NAME,"sample":paths.sample,"split":paths.split,"annotation_set":paths.annotation_set,"reviewed_frames":list(reviewed),"inference_id":paths.inference_id,
             "spacing_zyx_um":list(spacing),"production_model":production_model,"hypothesis_model":model_name,"motion":motion_metrics,"accepted_graph":accepted.metrics,"hypothesis_nodes":node_metrics,
             "geometry":geometry,"merge_signatures":sig,"top_features":sep.head(12).replace({np.nan:None}).to_dict(orient="records"),"hypothesis_cache":cache_manifest}
    atomic_json(paths.output/"summary.json",summary)
    print("\n"+"="*112); print("INVESTIGATION 45 — RESULTS"); print("="*112)
    print(f"merge components             : {sig['merge_components']}"); print(f"clean components             : {sig['clean_components']}")
    print(f"continuation raw/stable med  : {geometry['raw_median_um']:.3f} / {geometry['stable_median_um']:.3f} um")
    print(f"continuation raw/stable p90  : {geometry['raw_p90_um']:.3f} / {geometry['stable_p90_um']:.3f} um")
    print(f"fraction tighter compensated : {geometry['fraction_tighter_after_compensation']:.3f}")
    print(f"merge newborn rate           : {sig['merge_newborn_rate']:.3f}")
    print(f"merge retains parent         : {sig['merge_retains_parent_rate']:.3f}")
    print(f"merge multi plausible        : {sig['merge_multi_plausible_rate']:.3f} (clean={sig['clean_multi_plausible_rate']:.3f})")
    print(f"many-to-one suppressed       : {sig['merge_many_to_one_suppressed_rate']:.3f}")
    print(f"merge rejected plausible     : {sig['merge_rejected_plausible_rate']:.3f} (clean={sig['clean_rejected_plausible_rate']:.3f})")
    print(f"merge stable broken nearby   : {sig['merge_stable_broken_nearby_rate']:.3f} (clean={sig['clean_stable_broken_nearby_rate']:.3f})")
    print(f"merge parent volume >1.5x    : {sig['merge_parent_volume_gt_1p5_rate']:.3f} (clean={sig['clean_parent_volume_gt_1p5_rate']:.3f})")
    print(f"multi-volume explains better : {sig['merge_multi_volume_better_rate']:.3f} (clean={sig['clean_multi_volume_better_rate']:.3f})")
    print(f">=2 predicted centers inside : {sig['merge_predicted_centers_inside_ge2_rate']:.3f} (clean={sig['clean_predicted_centers_inside_ge2_rate']:.3f})")
    print("\nTop feature separation:")
    for r in sep.head(10).itertuples(index=False): print(f"  {r.feature:40s} AUC={r.oriented_auc:6.3f} {r.direction:15s} merge={r.merge_median:9.3f} clean={r.clean_median:9.3f}")
    print("\nOutputs:"); print(f"  {paths.output/'summary.json'}"); print(f"  {paths.output/'component_evidence.csv'}"); print(f"  {paths.output/'feature_separation.csv'}"); print(f"  {paths.output/'continuation_geometry.csv'}"); print(f"  {paths.cache}"); print("="*112)


def parser():
    p=argparse.ArgumentParser(description="Investigation 45: stabilized temporal geometry + Trackastra hypothesis evidence audit")
    p.add_argument("--data-root",type=Path,default=None); p.add_argument("--split",default=DEFAULT_SPLIT); p.add_argument("--sample-id",default=DEFAULT_SAMPLE); p.add_argument("--annotation-set",default=DEFAULT_ANNOTATION_SET)
    p.add_argument("--reviewed-frames",default=DEFAULT_REVIEWED); p.add_argument("--spacing-zyx-um",default=",".join(str(v) for v in DEFAULT_SPACING_ZYX_UM)); p.add_argument("--device",default="cuda"); p.add_argument("--batch-size",type=int,default=1)
    p.add_argument("--model-name",default=None); p.add_argument("--allow-model-override",action="store_true"); p.add_argument("--plausible-score-threshold",type=float,default=.20); p.add_argument("--strong-score-threshold",type=float,default=.50)
    p.add_argument("--near-radius-dref",type=float,default=2.5); p.add_argument("--top-k-predecessors",type=int,default=5); p.add_argument("--graph-match-error-um",type=float,default=.50); p.add_argument("--rebuild-hypothesis-cache",action="store_true"); p.add_argument("--output",type=Path,default=None)
    return p


if __name__ == "__main__":
    args=parser().parse_args()
    if args.batch_size<1: raise ValueError("--batch-size must be >=1")
    if not (0<=args.plausible_score_threshold<=args.strong_score_threshold<=1): raise ValueError("Require 0 <= plausible <= strong <= 1")
    if args.near_radius_dref<=0 or args.top_k_predecessors<1 or args.graph_match_error_um<=0: raise ValueError("Radius/top-k/match threshold arguments must be positive")
    main(args)
