import numpy as np
from scipy.ndimage import gaussian_filter


def estimate_background(
        volume: np.ndarray,
        voxel_size: tuple[float, float, float],
        sigma_um: float = 4.0,
) -> np.ndarray:
    """Return the smooth background generated by the production algorithm."""

    sigma = sigma_um / np.asarray(voxel_size)
    return gaussian_filter(volume, sigma=sigma)


def background_correction(
        volume: np.ndarray,
        voxel_size: tuple[float, float, float],
        sigma_um: float = 4.0,
) -> np.ndarray:
    """Subtract a smooth background estimate."""

    background = estimate_background(volume, voxel_size, sigma_um)

    corrected = volume - background

    corrected = np.clip(corrected, 0.0, None)

    if corrected.max() > 0:
        corrected /= corrected.max()

    return corrected


def background_correction_with_estimate(
        volume: np.ndarray,
        voxel_size: tuple[float, float, float],
        sigma_um: float = 4.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Correct once while retaining the background used by the algorithm."""

    background = estimate_background(volume, voxel_size, sigma_um)
    corrected = np.clip(volume - background, 0.0, None)
    if corrected.max() > 0:
        corrected /= corrected.max()
    return corrected, background
